PARTICLE_RADIUS_INDEX = 0
INTERACTION_RADIUS_INDEX = 1
FRICTION_COEFFICIENT_INDEX = 2
DISTANCE_INDEX = 3
COLOR_NUMBER_LOOKUP_START_INDEX = 4
COLOR_NUMBER_LOOKUP_ROW_LENGTH = 3
COLOR_INTERACTIONS_START_INDEX = 16
COLOR_INTERACTIONS_ROW_LENGTH = 4
